# Generated by Django 3.1.4 on 2020-12-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='avatar',
            field=models.ImageField(default='SeekPng.com_avatar-png_1150362.png', upload_to='images/avatars/'),
        ),
    ]
