# Generated by Django 3.1.4 on 2020-12-30 14:05

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_visitor_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='avatar',
            field=models.ImageField(default='SeekPng.com_avatar-png_1150362.png', storage=blog.models.MyFileSystemStorage('avatars/'), upload_to='images/avatars/'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('status', models.CharField(choices=[('dormant', 'Dormant'), ('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=10)),
                ('banner', models.ImageField(blank=True, default='', storage=blog.models.MyFileSystemStorage('banners/'), upload_to='images/banners/')),
                ('description', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_post', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
