# Generated by Django 3.1.4 on 2020-12-30 14:09

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201230_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(blank=True, default='', storage=blog.models.MyFileSystemStorage('images/banners/'), upload_to='images/banners/'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='avatar',
            field=models.ImageField(default='SeekPng.com_avatar-png_1150362.png', storage=blog.models.MyFileSystemStorage('images/avatars/'), upload_to='images/avatars/'),
        ),
    ]
