# Generated by Django 3.1.4 on 2021-01-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201231_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fans',
            field=models.ManyToManyField(blank=True, related_name='comments_liked', to='blog.Visitor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('deleted', 'deleted')], default='draft', max_length=10),
        ),
    ]
