# Generated by Django 3.1.4 on 2021-01-22 15:27

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210112_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, storage=blog.models.MyFileSystemStorage('images/banners/'), upload_to='images/banners/'),
        ),
    ]
