# Generated by Django 3.1.3 on 2020-12-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('pin', models.CharField(max_length=6)),
                ('last_visit', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-last_visit',),
            },
        ),
    ]
